/**
    Generated by: silvera
    Date: 2022-09-20 23:08:02
*/
package main

import (
    "context"
	"net/http"
    "bookstore/api"

    eureka "github.com/xuanbo/eureka-client"
    "go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func main() {
    eurekaClient := eureka.NewClient(&eureka.Config{
        DefaultZone:           "http://localhost:9091/eureka/",
        App:                   "bookstore",
        Port:                  50000,
        RenewalIntervalInSecs: 10,
        DurationInSecs:        30,
        Metadata: map[string]interface{}{
            "VERSION":              "0.0.1b",
            "NODE_GROUP_ID":        0,
            "PRODUCT_CODE":         "DEFAULT",
            "PRODUCT_VERSION_CODE": "DEFAULT",
            "PRODUCT_ENV_CODE":     "DEFAULT",
            "SERVICE_VERSION_CODE": "DEFAULT",
        },
    })
    eurekaClient.Start()

    ctx := context.Background()
    mongoClient, _ := mongo.Connect(ctx, options.Client().ApplyURI("mongodb://localhost:27017"))
    database := mongoClient.Database("bookstore-db")

    srv := api.NewServer(database)
    http.ListenAndServe(":50000", srv)
}