/**
    Generated by: silvera
    Date: 2022-09-20 23:08:02
*/
package api

import (
	"bookstore/api/controllers"

	"github.com/gorilla/mux"
	"go.mongodb.org/mongo-driver/mongo"
)

type Server struct {
	*mongo.Database
	*mux.Router
	*controllers.BookstoreController
}

func NewServer(database *mongo.Database) *Server {
	s := &Server{
		Router: mux.NewRouter(),
		Database: database,
		BookstoreController: controllers.NewBookstoreController(database),
	}
	s.routes()
	return s
}

func (s *Server) routes() {
    // Auto-generated CRUD routes
    s.HandleFunc("/books", s.BookstoreController.CreateBook()).Methods("POST")
    s.HandleFunc("/books/{id}", s.BookstoreController.GetBook()).Methods("GET")
    s.HandleFunc("/books", s.BookstoreController.UpdateBook()).Methods("PUT")
    s.HandleFunc("/books/{id}", s.BookstoreController.DeleteBook()).Methods("DELETE")

    // Auto-generated custom routes
    s.HandleFunc("/listbooks", s.BookstoreController.ListBooks()).Methods("GET")
    s.HandleFunc("/bookexists", s.BookstoreController.BookExists()).Methods("GET")
    s.HandleFunc("/bookprice", s.BookstoreController.BookPrice()).Methods("GET")
}